[package]
name = "libdopamine"
version = "0.1.1"
edition = "2021"

[dependencies.windows]
version = "0.*"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
]

